export const REGISTER_FAILD = 'REGISER_FAILD_ERROR';
export const HTTP_SERVER = 'HTTP_SERVER';
export const HTTPS_SERVER = 'HTTPS_SERVER';
export const ATTACH_SSL_FAILD = 'ATTACH_SSL_FAILD';
export const CREATE_SECURE_CONTEXT_FAILD = 'CREATE_SECURE_CONTEXT_FAILD';
